### ISSUE TITLE
coverageDirectory is being ignored from the CLI

### ISSUE THREAD

**Issue by thiagodp** [sh33dafi/jest-sonar#20]
**Describe the bug**

Report file is being created in the current/root directory when receiving the target directory from the command line.

**To Reproduce**
```
jest --coverage --coverageDirectory=\"coverage\" --reporters=\"default\" --reporters=\"jest-sonar\"
```
`sonar-report.xml` is being created in the current directory rather than in `coverage`.

**Expected behavior**
Generate `sonar-report.xml` into the parameterized directory.

**Desktop (please complete the following information):**
 - OS: Windows
- NodeJS version 12

**Comment by sh33dafi** [comment]
@thiagodp should be fixed in https://github.com/sh33dafi/jest-sonar/releases/tag/v0.2.7

**Comment by thiagodp** [comment]
@sh33dafi Thank you!
