### ISSUE TITLE
Generate report using full path

### ISSUE THREAD

**Issue by erichans** [sh33dafi/jest-sonar#23]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
It would be good if we could generate the test-report.xml using the full file path or have an way to configure to use either relative or absolute file path.

**Describe alternatives you've considered**

I'm trying to move from the jest-sonar-reporter because they archived their repo.

My project is a multimodule one with 2 modules completely independent and the code to run the tests is in the modules because they have their differences.

When I run the tests from the modules, the report generates the file paths relative to the respective module root and not relative to the project root.

The problem is that sonarqube no longer understands modules and sees only the entire project.
So I can't configure like this:
module1.sonar.testExecutionReportPaths=testpath1
module2.sonar.testExecutionReportPaths=testpath2

I have to configure it globally:
sonar.testExecutionReportPaths=pathmodule1/testpath1,pathmodule2/testpath2

Otherwise it ignores my properties.

Is it possible to have a flag to configure if it should generate path absolute or relative to avoid breaking changes?

Thanks in advance

**Additional context**
Sonar is dropping modules support: https://jira.sonarsource.com/browse/MMF-365
The test report sensors are global now: https://jira.sonarsource.com/browse/SONAR-11530

**Comment by sh33dafi** [comment]
So if I understand correctly you want to have the file path absolute and not relative to the root of the project
e.g. `<file path=\\"/Users/foo/dev/est-sonar/my-test/my-test.spec.js\\">` 

I will add a config param so you can configure how to generate the path

`reporters: ['default',  ['jest-sonar', {
         reportedFilePath: 'relative|absolute'
     }]],`

something like above default will be 'relative'
