### ISSUE TITLE
Ability to specify root path for relative reported file path

### ISSUE THREAD

**Issue by elyzov** [sh33dafi/jest-sonar#28]
**Is your feature request related to a problem? Please describe.**
I have mono-repository with backend and frontend parts placed in different folders (e.g. `src/ui`).
I install and configure **jest-sonar** reporter in the following way

```
    ...
    "reporters": [
      "default",
      [
        "jest-sonar",
        {
          "outputDirectory": ".jest",
          "reportedFilePath": "relative"
        }
      ]
    ],
    ...
```
And then I run tests from the root of the project like this

```
yarn --cwd src/ui/ test
```

But relative path generates based on the `rootDir` specified in the config, so **sonar-scanner** cannot find those files and skip its.

**Describe the solution you'd like**
I want to add additional option like `relativeRootPath`, which will be used instead of `rootDir` if specified.

Thus, I could change my config like this

```
    ...
    "reporters": [
      "default",
      [
        "jest-sonar",
        {
          "outputDirectory": ".jest",
          "reportedFilePath": "relative",
          "relativeRootPath": "../../"
        }
      ]
    ],
    ...
```

and all would be worked as it should.

**Comment by sh33dafi** [comment]
Fixed in https://github.com/sh33dafi/jest-sonar/pull/29

**Comment by elyzov** [comment]
Could you release new version with this feature, that I could use it in my project?

**Comment by sh33dafi** [comment]
> Could you release new version with this feature, that I could use it in my project?
https://www.npmjs.com/package/jest-sonar/v/0.2.11
